### ISSUE TITLE
Buttom IM6001-BTP issue

### ISSUE THREAD

**Issue by MartinWinkel** [AdyRock/com.smartthings#10]
Hej Adrian

Sorry if it gets a little short, but my English is not super good and I use google translate

I just have a little problem with Buttom (IM6001-BTP) it measures the temperature and battery fine.
but the pressing function, do not work, if you have time to fix it, I would be a very happy man.
Thank you so much for what it have done, than until now

One of your biggest fan from denmark
Martin

**Comment by AdyRock** [comment]
It's probably because the status changes in between polling so Homey doesn't see it. 
The rate limit means the app can only check every  5 seconds. 
I would like to get subscriptions working but Samsung makes that extremely difficult and I haven't managed yet.
