### ISSUE TITLE
Refreshing of the app is not working

### ISSUE THREAD

**Issue by Arjan-21** [AdyRock/com.smartthings#14]
After two weeks my samsung washing machine is not working on Homey anymore. I really loved this app, because I can make my washing machine smarter.
Just added the device again (with a new token). After adding Homey will see the washing machine is running and the complete time. But it didn't see the wash machine is finished or started again. 

The only problem I can think of is the polling. it was 30, but changed it to 60. 
I've a samsung tv but use a different homey app and token (can't change the polling with this app).

I don't know or the polling is the problem, but was the only thing I know for now.

**Comment by AdyRock** [comment]
Could you enable the log, wait for it to populate and then copy and past it to a reply.
My washing machine is still reporting OK so I don't think Samsung have made any breaking changes.
My polling interval is 15 seconds.

I also use the Samsung SmartTV app for my TV as it is an older model that is not compatible with ST.

**Comment by Arjan-21** [comment]
Thanks for your comment.

This is my whole log file. The 401 code was when I was trying or the code was wrong. I've removed the info from the tv

* devices
* HTTPS Error: 401: Unauthorized
* Setting BearerToken has changed.
* devices
* Found device: 
* {
  "deviceId": "1f834bcc-87ee-913c-a352-ffafb5c04466",
  "name": "[washer] Samsung",
  "label": "Wasmachine",
  "manufacturerName": "Samsung Electronics",
  "presentationId": "DA-WM-WM-000001",
  "deviceManufacturerCode": "Samsung Electronics",
  "locationId": "c815940b-182f-4723-9e63-a6647861faa9",
  "ownerId": "9adde02a-3c33-909f-193e-3c9f9fa93da3",
  "roomId": "cfed1710-50a7-4d2f-b633-048d1184c588",
  "deviceTypeName": "Samsung OCF Washer",
  "components": [
    {
      "id": "main",
      "capabilities": [
        {
          "id": "execute",
          "version": 1
        },
        {
          "id": "ocf",
          "version": 1
        },
        {
          "id": "powerConsumptionReport",
          "version": 1
        },
        {
          "id": "refresh",
          "version": 1
        },
        {
          "id": "remoteControlStatus",
          "version": 1
        },
        {
          "id": "switch",
          "version": 1
        },
        {
          "id": "washerOperatingState",
          "version": 1
        },
        {
          "id": "custom.disabledCapabilities",
          "version": 1
        },
        {
          "id": "custom.dryerDryLevel",
          "version": 1
        },
        {
          "id": "custom.jobBeginningStatus",
          "version": 1
        },
        {
          "id": "custom.supportedOptions",
          "version": 1
        },
        {
          "id": "custom.washerAutoDetergent",
          "version": 1
        },
        {
          "id": "custom.washerAutoSoftener",
          "version": 1
        },
        {
          "id": "custom.washerRinseCycles",
          "version": 1
        },
        {
          "id": "custom.washerSoilLevel",
          "version": 1
        },
        {
          "id": "custom.washerSpinLevel",
          "version": 1
        },
        {
          "id": "custom.washerWaterTemperature",
          "version": 1
        },
        {
          "id": "samsungce.autoDispenseDetergent",
          "version": 1
        },
        {
          "id": "samsungce.autoDispenseSoftener",
          "version": 1
        },
        {
          "id": "samsungce.detergentOrder",
          "version": 1
        },
        {
          "id": "samsungce.detergentState",
          "version": 1
        },
        {
          "id": "samsungce.deviceIdentification",
          "version": 1
        },
        {
          "id": "samsungce.driverVersion",
          "version": 1
        },
        {
          "id": "samsungce.kidsLock",
          "version": 1
        },
        {
          "id": "samsungce.softenerOrder",
          "version": 1
        },
        {
          "id": "samsungce.softenerState",
          "version": 1
        },
        {
          "id": "samsungce.washerBubbleSoak",
          "version": 1
        },
        {
          "id": "samsungce.washerCycle",
          "version": 1
        },
        {
          "id": "samsungce.washerCyclePreset",
          "version": 1
        },
        {
          "id": "samsungce.washerWashingTime",
          "version": 1
        },
        {
          "id": "samsungce.washerWaterLevel",
          "version": 1
        },
        {
          "id": "samsungce.washerWaterValve",
          "version": 1
        },
        {
          "id": "samsungce.welcomeMessage",
          "version": 1
        },
        {
          "id": "samsungce.waterConsumptionReport",
          "version": 1
        }
      ],
      "categories": [
        {
          "name": "Washer",
          "categoryType": "manufacturer"
        }
      ]
    }
  ],
  "createTime": "2020-12-18T10:02:24.391Z",
  "profile": {
    "id": "d5952b45-08c2-31bc-81e3-63805e8d83f8"
  },
  "type": "OCF",
  "restrictionTier": 0
}
  "dth": {
    "completedSetup": false,
    "deviceNetworkType": "UNKNOWN",
    "deviceTypeId": "8a9d4b1e3bfce38a013bfce42d360015",
    "deviceTypeName": "Mobile Presence",
    "executingLocally": false,
    "networkSecurityLevel": "UNKNOWN"
  },
  "type": "DTH",
  "restrictionTier": 0
}
* [object Object],[object Object],[object Object]
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/powerConsumptionReport/status
* {
  "powerConsumption": {
    "value": {
      "energy": 91700,
      "deltaEnergy": 0,
      "power": 0,
      "powerEnergy": 0,
      "persistedEnergy": 0,
      "energySaved": 0,
      "start": "2021-05-23T14:03:27Z",
      "end": "2021-05-23T14:18:28Z"
    },
    "timestamp": "2021-05-23T14:18:28.393Z"
  }
}
* Set Capability: measure_power - Value: 0
* Set Capability: meter_power - Value: 91.7
* Set Capability: meter_power.delta - Value: 0
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/remoteControlStatus/status
* {
  "remoteControlEnabled": {
    "value": "false",
    "timestamp": "2021-05-09T19:11:03.748Z"
  }
}
* Set Capability: remote_status - Value: false
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/switch/status
* {
  "switch": {
    "value": "on",
    "timestamp": "2021-05-23T12:48:19.482Z"
  }
}
* Set Capability: onoff - Value: true
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/washerOperatingState/status
* {
  "completionTime": {
    "value": "2021-05-23T15:01:02Z",
    "timestamp": "2021-05-23T14:26:02.840Z"
  },
  "machineState": {
    "value": "run",
    "timestamp": "2021-05-23T12:48:19.555Z"
  },
  "washerJobState": {
    "value": "rinse",
    "timestamp": "2021-05-23T14:21:49.046Z"
  },
  "supportedMachineStates": {
    "value": null,
    "timestamp": "2020-11-29T12:28:56.424Z"
  }
}
* Set Capability: washer_job_status - Value: rinse
* Set Capability: completion_time - Value: 17:01 23-04
* Set Capability: washer_status - Value: run
* Trigger Check: washer_status = 
* Trigger change: washer_status = run
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/custom.washerRinseCycles/status
* {
  "supportedWasherRinseCycles": {
    "value": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "timestamp": "2020-11-29T12:28:51.972Z"
  },
  "washerRinseCycles": {
    "value": "2",
    "timestamp": "2021-05-17T08:09:49.299Z"
  }
}
* Set Capability: rinse_cycles - Value: 2
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/custom.washerSpinLevel/status
* {
  "washerSpinLevel": {
    "value": "1600",
    "timestamp": "2021-05-23T10:30:57.234Z"
  },
  "supportedWasherSpinLevel": {
    "value": [
      "rinseHold",
      "noSpin",
      "400",
      "800",
      "1000",
      "1200",
      "1400",
      "1600"
    ],
    "timestamp": "2020-11-29T12:28:51.972Z"
  }
}
* Set Capability: spin_level - Value: 1600
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/custom.washerWaterTemperature/status
* {
  "supportedWasherWaterTemperature": {
    "value": [
      "none",
      "cold",
      "20",
      "30",
      "40",
      "60",
      "90"
    ],
    "timestamp": "2020-11-29T12:28:51.972Z"
  },
  "washerWaterTemperature": {
    "value": "40",
    "timestamp": "2021-05-23T10:30:54.288Z"
  }
}
* Set Capability: water_temperature - Value: 40
* devices/1f834bcc-87ee-913c-a352-ffafb5c04466/components/main/capabilities/samsungce.washerCycle/status
* {
  "supportedCycles": {
    "value": [
      {
        "cycle": "D0",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "35F0",
            "default": "off",
            "options": [
              "on",
              "off"
            ]
          },
          "spinLevel": {
            "raw": "A7FF",
            "default": "1600",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400",
              "1600"
            ]
          },
          "rinseCycle": {
            "raw": "923F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "847E",
            "default": "40",
            "options": [
              "cold",
              "20",
              "30",
              "40",
              "60",
              "90"
            ]
          }
        }
      },
      {
        "cycle": "DC",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A33F",
            "default": "800",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200"
            ]
          },
          "rinseCycle": {
            "raw": "933F",
            "default": "3",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "811E",
            "default": "cold",
            "options": [
              "cold",
              "20",
              "30",
              "40"
            ]
          }
        }
      },
      {
        "cycle": "DB",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "35F0",
            "default": "off",
            "options": [
              "on",
              "off"
            ]
          },
          "spinLevel": {
            "raw": "A67F",
            "default": "1400",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400"
            ]
          },
          "rinseCycle": {
            "raw": "923F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "841E",
            "default": "40",
            "options": [
              "cold",
              "20",
              "30",
              "40"
            ]
          }
        }
      },
      {
        "cycle": "DA",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A53F",
            "default": "1200",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200"
            ]
          },
          "rinseCycle": {
            "raw": "923F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "8102",
            "default": "cold",
            "options": [
              "cold"
            ]
          }
        }
      },
      {
        "cycle": "D8",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A30F",
            "default": "800",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800"
            ]
          },
          "rinseCycle": {
            "raw": "920F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3"
            ]
          },
          "waterTemperature": {
            "raw": "841E",
            "default": "40",
            "options": [
              "cold",
              "20",
              "30",
              "40"
            ]
          }
        }
      },
      {
        "cycle": "D7",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A57F",
            "default": "1200",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400"
            ]
          },
          "rinseCycle": {
            "raw": "920F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3"
            ]
          },
          "waterTemperature": {
            "raw": "831E",
            "default": "30",
            "options": [
              "cold",
              "20",
              "30",
              "40"
            ]
          }
        }
      },
      {
        "cycle": "D6",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "35F0",
            "default": "off",
            "options": [
              "on",
              "off"
            ]
          },
          "spinLevel": {
            "raw": "A30F",
            "default": "800",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800"
            ]
          },
          "rinseCycle": {
            "raw": "933F",
            "default": "3",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "841E",
            "default": "40",
            "options": [
              "cold",
              "20",
              "30",
              "40"
            ]
          }
        }
      },
      {
        "cycle": "E4",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "35F0",
            "default": "off",
            "options": [
              "on",
              "off"
            ]
          },
          "spinLevel": {
            "raw": "A67F",
            "default": "1400",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400"
            ]
          },
          "rinseCycle": {
            "raw": "943F",
            "default": "4",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "8560",
            "default": "60",
            "options": [
              "60",
              "90"
            ]
          }
        }
      },
      {
        "cycle": "D5",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A520",
            "default": "1200",
            "options": [
              "1200"
            ]
          },
          "rinseCycle": {
            "raw": "9204",
            "default": "2",
            "options": [
              "2"
            ]
          },
          "waterTemperature": {
            "raw": "8520",
            "default": "60",
            "options": [
              "60"
            ]
          }
        }
      },
      {
        "cycle": "BA",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A6FF",
            "default": "1400",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400",
              "1600"
            ]
          },
          "rinseCycle": {
            "raw": "9000",
            "options": []
          },
          "waterTemperature": {
            "raw": "8000",
            "options": []
          }
        }
      },
      {
        "cycle": "D4",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A6FF",
            "default": "1400",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400",
              "1600"
            ]
          },
          "rinseCycle": {
            "raw": "913F",
            "default": "1",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "8000",
            "options": []
          }
        }
      },
      {
        "cycle": "D3",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A30F",
            "default": "800",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800"
            ]
          },
          "rinseCycle": {
            "raw": "920F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3"
            ]
          },
          "waterTemperature": {
            "raw": "831E",
            "default": "30",
            "options": [
              "cold",
              "20",
              "30",
              "40"
            ]
          }
        }
      },
      {
        "cycle": "D2",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "35F0",
            "default": "off",
            "options": [
              "on",
              "off"
            ]
          },
          "spinLevel": {
            "raw": "A67F",
            "default": "1400",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400"
            ]
          },
          "rinseCycle": {
            "raw": "923F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "843E",
            "default": "40",
            "options": [
              "cold",
              "20",
              "30",
              "40",
              "60"
            ]
          }
        }
      },
      {
        "cycle": "D1",
        "supportedOptions": {
          "bubbleSoak": {
            "raw": "3500",
            "options": []
          },
          "spinLevel": {
            "raw": "A7FF",
            "default": "1600",
            "options": [
              "rinseHold",
              "noSpin",
              "400",
              "800",
              "1000",
              "1200",
              "1400",
              "1600"
            ]
          },
          "rinseCycle": {
            "raw": "923F",
            "default": "2",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5"
            ]
          },
          "waterTemperature": {
            "raw": "8430",
            "default": "40",
            "options": [
              "40",
              "60"
            ]
          }
        }
      }
    ],
    "timestamp": "2021-04-17T17:24:14.452Z"
  },
  "washerCycle": {
    "value": "Table_00_Course_D1",
    "timestamp": "2021-05-23T10:30:56.970Z"
  },
  "referenceTable": {
    "value": {
      "id": "Table_00"
    },
    "timestamp": "2021-04-02T11:00:01.464Z"
  }
}
* Set Capability: washer_mode - Value: Table_00_Course_D1

**Comment by AdyRock** [comment]
At a quick glance, what is there looks fine but it does appear the polling is not running. Can you try setting the polling back to 30 or down to 15 to see if it makes any difference. 
You should see the log update on every polling cycle so even if nothing is changing it should be obvious if it is polling.

**Comment by Arjan-21** [comment]
I’ve update the polling to 15 times and delete the log after that. But don’t see a new log anymore. So I think it isn’t updating.


Edit:
I’ve a new log with some errors. I’m going to look what the errors mean.

* {"commands":[{"component":"main","capability":"switch","command":"off","arguments":[]}]}
* [object Object]
* HTTPS Error: 409: 
* Wasmachine onCapabilityOnoff Error {
  "statusCode": 409,
  "statusMessage": "HTTPS Error: "
}

**Comment by Arjan-21** [comment]
I thought I've seen a site where all the errors are, but unfortunately I can't find it.

**Comment by Arjan-21** [comment]
It was a polling issue. After a week the wasmachine is working again. Thanks for your help.

**Comment by AdyRock** [comment]
Glad it's working again. Had me totally stumped, I must admit. I can't find why the polling would stop.

**Comment by Arjan-21** [comment]
I think it was the maximum of polling request. It’s the only thing I can think about when it starts working after a week.

**Comment by AdyRock** [comment]
Maybe, but the app should ensure it doesn't exceed the limits. I will check the ST documents again to make sure they haven't changed the rules.
