### ISSUE TITLE
Missing support for SmartthingsMultipurpose Sensor

### ISSUE THREAD

**Issue by steeleking** [AdyRock/com.smartthings#17]
Will i t be possible to add support for Smartthings Multipurpose Sensor?

I have one, and it adds to Homey, but not with all capabilities.
Is there any way I can update/add capability my self, via **CLI** or **tools.developer.homey.app/tools/api-playground** ?

It should have Capablity like this:
(from Smarthings Hub )
**contact**: closed
**acceleration**: inactive
**threeAxis**: [1035,22,-38] mG
**battery**: 66 %
**checkInterval**: 720 s
**temperature**: 19.7 C

But all I get in Homey is contact, battery an temperature

  "deviceId": "9143520e-71e7-443b-bb4a-0feacf9eb91c",
  "name": "Multipurpose Sensor",
  "label": "Door vaskerom",
  "manufacturerName": "SmartThings",
  "presentationId": "SmartThings-smartthings-SmartSense_Multi_Sensor",
  "deviceManufacturerCode": "Samjin",
  "locationId": "18405ae2-7c7a-4d92-b634-8c17c2cde84e",
  "roomId": "328d91b6-77db-4e7e-ae22-e745372753c6",
  "deviceTypeId": "52517166-43f9-4cbf-8bc2-7da4e8df5614",
  "deviceTypeName": "SmartSense Multi Sensor",
  "deviceNetworkType": "ZIGBEE",
  "components": [
    {
      "id": "main",
      "label": "Door vaskerom",
      "capabilities": [
        {
          "id": "temperatureMeasurement",
          "version": 1
        },
        {
          "id": "battery",
          "version": 1
        },
        {
          "id": "contactSensor",
          "version": 1
        },
        {
          "id": "configuration",
          "version": 1
        },
        {
          "id": "threeAxis",
          "version": 1
        },
        {
          "id": "accelerationSensor",
          "version": 1
        },
        {
          "id": "refresh",
          "version": 1
        },
        {
          "id": "sensor",
          "version": 1
        },
        {
          "id": "healthCheck",
          "version": 1
        }
      ],
      "categories": [
        {
          "name": "MultiFunctionalSensor",
          "categoryType": "manufacturer"
        }
      ]

**Comment by AdyRock** [comment]
I will see what I can do but again the polling interval of 15 seconds may make it impractical to use.

**Comment by AdyRock** [comment]
I have published an update in the HCS. It should find the accelerometers now but I have no idea if it will work as I can't test it.
Let me know how it goes.

**Comment by steeleking** [comment]
Fantastic !!
Tried and it works. Both the Multiperpose Sensor, AND the WaterLeak sensor  :-)
Thanks for really quick response and and update @AdyRock , amazing work !!
I'd like to learn to do that my self one day   :-) 

I have another question tho, and maybe this isnt the right place, but would it be hard to wright an app/driver that can talk to Smartthings Zigbee devices without the Smartthings Hub ? 
The whole reason I baught Homey was so that I could get rid of all the other Hubs I've got   :-)
So far, I can't get rid of even one........

Anyway, thanks again !!

**Comment by AdyRock** [comment]
In theory, yes. Homey should be able to control the ZigBee devices directly. I haven't delved into ZigBee at all as I don't have any of those devices, so I'm not sure what is involved.
The Homey API does seem to provide good support for ZigBee, so maybe you could get the source code of an existing app from GitHub and have a go at modifying it.
I use VS Code to edit the source code as it is free and easy to use plus has integrated debugging tools.
All the help and tools for developing apps are found on https://tools.developer.homey.app/

**Comment by steeleking** [comment]
Thanks, I will have a look at it, would be fun to be able to do some programming to help my self (and others :-) ) , 20 years since I worked with programming, so I'm little bit rusty you can say   :-)

**Comment by AdyRock** [comment]
I find programming for Homey very addictive and my wife would say I spend far too much time 'playing' :-)
Let me know if you need any help setting up the environment.
