### ISSUE TITLE
Kan geen apparaten installeren

### ISSUE THREAD

**Issue by mcrbrauers** [AdyRock/com.smartthings#18]
It's impossible to add any smartthings device.
Each time when I want to install a device I get the message: Unknown Error

Please help me to avoid this error and install my devices.

I've tried to fix the problem by rebooting Homey

**Comment by AdyRock** [comment]
You need to follow the instructions in the readme.txt file that show how to get the API code from SmartThings and enter that into the Configure App page.

**Comment by mcrbrauers** [comment]
I made a misstake by typing the API code. 
Thanks for the help!
