### ISSUE TITLE
polling error

### ISSUE THREAD

**Issue by Strike2001** [AdyRock/com.smartthings#19]
The device states are not polling , the log says polling error {}
next intervall : 5000

**Comment by AdyRock** [comment]
Hmm, I seem to be getting the same issue. I will look in to it but it could be an issue with SmartThings.

**Comment by Strike2001** [comment]
is it also possible to complete Tv funktions ? here is a copy from detected. 
Its the brand new miniQLED Series from 2021

it would be nice input/volume changes to get for some rulez but the biggest thing would be to send message to tv screen . 

im using your it with my samsung washer QuickDrive and your app works great . hope you can help . 

     "deviceId": "b750e2c0-5748-5b49-4b79-85429822154d",
      "name": "Samsung QN95AA 55 TV",
      "label": "Samsung QN95AA 55 TV",
      "manufacturerName": "Samsung Electronics",
      "presentationId": "VD-STV-2021",
      "deviceManufacturerCode": "Samsung Electronics",
      "locationId": "65e93940-304f-4004-bfcb-9dc052c895fa",
      "ownerId": "9c6c0175-60c2-5232-bdde-e02f70fdc363",
      "roomId": "02dda0a4-2237-43e0-aeb4-76755b00db5d",
      "deviceTypeName": "Samsung OCF TV",
      "components": [
        {
          "id": "main",
          "capabilities": [
            {
              "id": "ocf",
              "version": 1
            },
            {
              "id": "switch",
              "version": 1
            },
            {
              "id": "audioVolume",
              "version": 1
            },
            {
              "id": "audioMute",
              "version": 1
            },
            {
              "id": "tvChannel",
              "version": 1
            },
            {
              "id": "mediaInputSource",
              "version": 1
            },
            {
              "id": "mediaPlayback",
              "version": 1
            },
            {
              "id": "mediaTrackControl",
              "version": 1
            },
            {
              "id": "custom.error",
              "version": 1
            },
            {
              "id": "custom.picturemode",
              "version": 1
            },
            {
              "id": "custom.soundmode",
              "version": 1
            },
            {
              "id": "custom.accessibility",
              "version": 1
            },
            {
              "id": "custom.launchapp",
              "version": 1
            },
            {
              "id": "custom.recording",
              "version": 1
            },
            {
              "id": "custom.tvsearch",
              "version": 1
            },
            {
              "id": "custom.disabledCapabilities",
              "version": 1
            },
            {
              "id": "samsungvd.ambient",
              "version": 1
            },
            {
              "id": "samsungvd.ambientContent",
              "version": 1
            },
            {
              "id": "samsungvd.mediaInputSource",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "execute",
              "version": 1
            },
            {
              "id": "samsungvd.firmwareVersion",
              "version": 1
            },
            {
              "id": "samsungvd.supportsPowerOnByOcf",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Television",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2021-10-13T20:37:49.592Z",
      "profile": {
        "id": "bc8dff8e-eb2e-3c8d-a15b-3513c8888fb9"
      },
      "type": "OCF",
      "restrictionTier": 0
    },
    {

**Comment by AdyRock** [comment]
Strange, mine was showing the error because I have been updating it to Homey SDK3 and I had missed one of the changes, but I haven't released that code yet so not sure if it's the same problem you have.

The app should support the TV volume and channels already.
I don't know if it's possible to send a message to the TV via the API. I will look into it but I can't see anything obvious in the log.

**Comment by Strike2001** [comment]
thx for your work , 👍👍 i searched on the api and can say that all tizen OS do not support messages or info banners 😭 but i found a workaround with the new multiview mode left : app , inputs,... other side you show  the gallery app with a prefered picture ( Big doorbell 🙃) and after some seconds it flashed back to on signal input or last app,.... )

what i also can say that Samsung changed some id s on the tv (app_id... )now because homebridge plugin or the homey samsung app can not open some apps , if the tv changed (disney+ ) you get also an error because the command answer failed (success , failed,...) 
i little bit crazy what they do 🙈.
But all is better than a LG webos where the screensaver starts after inactive video 1-2min 😂 reading websites is not possible or the tv recognized not that a video is playing and kicks you out of netflix ... or a browser that can only 4 tabs and random crashes comes to .magic remote must reconnect randomly. that can the samsung tv better in some cases . but i will call the dev support from smartthings if there is any option to get 10/2021 Tv get really smart( a big ? i asked me why the hell all new tv have so stupid remotes , and quick options . for example i don t need a netflix / amazon or samsung tv button on my remote a quickmenu to change picture options ,energy savings .. at night with full 100% i need a sunglass🤣. and the stupid voice service i ever testet bixby 🤣🤣🤣 same as alexa but understand nothing what you say best ever🤣. when they now used the harrypoter remote ob webos to move mousepointer they would shoot up all 🤦‍♂️ but the named it smart tv .i first question i would asked them how i can use right the smartings app on tv . only turn on/off of devices is ... 🤦‍♂️ but the new remote don let you change the devices colour , brightness . and this with remote access please 🤣🤣🤣. 
So what do i learn , next would not be a tv and if some features would bot changed / corrected asap the get back the tv . and i buy a big monitor ( odyssey g9 maybe 🤔) i don t look at A+++ or or this shit 🤦‍♀️ the GQ55qn has G🤣 ( and every picture mode change must confirm twice with a notify that the energy got more ( even if you set all to low🤦‍♂️ brightness from 50 to 2 would cost more energypower : no words more) but if you want to know what they say to this stupid errors i let you know 🤔🙃 ( i can imagine what the first thing they said : please go into service menu by click ....) when they do this i kill them all.
When i by a new tv i decide which app installed or not and not they. and must handle because i have a special GEZ contract where they look if you have tuners or apps that can show their program.( so all ard zdf must deleted from tv also samsung tv app and some more ) LG has also changed on my old webos tv some features by service menus ( tuner deactivated , some DNS records and tracking sites they used for static.) and this via judicial orderbase ( German laws make it possible🤣)

so every app option you can modify , reading states , would make all S.Tv users happy . so look what you can do when you time offer's it ( Christmas, holiday,family comes first 😉) and if you have some tricks / infos or else let me know plz.
