### ISSUE TITLE
Samsung refrigerator

### ISSUE THREAD

**Issue by SunEast73** [AdyRock/com.smartthings#22]
Hello. Have a fridge that I added in the homey with no problem. It does not display temperature and does not detect when the door is opened or closed. Any suggestions for fixing this?

**Comment by AdyRock** [comment]
In the Homey app, could you first go through the Add Device procedure (no need to actually add anything) but get to the screen where it lists the discovered devices) and then open More > Apps > SmartThings > Configure App > Detected. Copy the contents of the log and paste into a reply. That should show me what capabilities the lock has so I can add them to the app.
Note: the information is harmless without your account key but if you want to remove any ID then that is not a problem.

**Comment by SunEast73** [comment]
Thank you!

I have "removed" ID ;-)

Here it is:

{
  "items": [
    {
      "deviceId": "Removed",
      "name": "Kjøleskap",
      "label": "Kjøleskap",
      "manufacturerName": "Samsung Electronics",
      "presentationId": "DA-REF-NORMAL-100001",
      "deviceManufacturerCode": "Samsung Electronics",
      "locationId": "removed",
      "roomId": "removed",
      "deviceTypeName": "Samsung OCF Refrigerator",
      "components": [
        {
          "id": "main",
          "label": "main",
          "capabilities": [
            {
              "id": "contactSensor",
              "version": 1
            },
            {
              "id": "execute",
              "version": 1
            },
            {
              "id": "ocf",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "refrigeration",
              "version": 1
            },
            {
              "id": "thermostatCoolingSetpoint",
              "version": 1
            },
            {
              "id": "custom.disabledCapabilities",
              "version": 1
            },
            {
              "id": "custom.disabledComponents",
              "version": 1
            },
            {
              "id": "custom.waterFilter",
              "version": 1
            },
            {
              "id": "samsungce.driverVersion",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Refrigerator",
              "categoryType": "manufacturer"
            }
          ]
        },
        {
          "id": "freezer",
          "label": "freezer",
          "capabilities": [
            {
              "id": "contactSensor",
              "version": 1
            },
            {
              "id": "thermostatCoolingSetpoint",
              "version": 1
            },
            {
              "id": "custom.disabledCapabilities",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Other",
              "categoryType": "manufacturer"
            }
          ]
        },
        {
          "id": "cooler",
          "label": "cooler",
          "capabilities": [
            {
              "id": "contactSensor",
              "version": 1
            },
            {
              "id": "thermostatCoolingSetpoint",
              "version": 1
            },
            {
              "id": "custom.disabledCapabilities",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Other",
              "categoryType": "manufacturer"
            }
          ]
        },
        {
          "id": "cvroom",
          "label": "cvroom",
          "capabilities": [
            {
              "id": "contactSensor",
              "version": 1
            },
            {
              "id": "thermostatCoolingSetpoint",
              "version": 1
            },
            {
              "id": "custom.disabledCapabilities",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Other",
              "categoryType": "manufacturer"
            }
          ]
        },
        {
          "id": "onedoor",
          "label": "Refrigerator One Door",
          "capabilities": [
            {
              "id": "contactSensor",
              "version": 1
            },
            {
              "id": "thermostatCoolingSetpoint",
              "version": 1
            },
            {
              "id": "custom.disabledCapabilities",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Other",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2019-08-16T20:06:02Z",
      "profile": {
        "id": "removed"
      },
      "type": "OCF",
      "restrictionTier": 0
    }
  ],
  "_links": {}
}

**Comment by AdyRock** [comment]
There are several components listed:
"main",
"freezer",
"cooler",
"cvroom",
"onedoor"

Based on what you know about the fridge could you have a guess at what each component relates to?

I am guessing it is a fridge / freezer combination.

Can you try to add it using the SmartThings Device option. Then enable the logging and send me the log (blue tick) after it has captured the settings.

**Comment by SunEast73** [comment]
hi and thanks for the reply. There is only a fridge and no freezer. Tried to add only "cooler" and then it works with the contact alarm on the door. So then it works great!
