### ISSUE TITLE
Smarttag

### ISSUE THREAD

**Issue by Corneliusmor** [AdyRock/com.smartthings#23]
Hello. 

The app adds my smarttag, but as a device with 2 buttons ( volumen up and down ) neither works.. 

Can it be corrected to work ?

**Comment by AdyRock** [comment]
In the Homey app, could you first go through the Add Device procedure (no need to actually add anything) but get to the screen where it lists the discovered devices) and then open More > Apps > SmartThings > Configure App > Detected. Copy the contents of the log and paste into a reply. That should show me what capabilities the lock has so I can add them to the app.
Note: the information is harmless without your account key but if you want to remove any ID then that is not a problem.

I will ad this a sticky post so it easier for users to find out how to send the information to me.

**Comment by Corneliusmor** [comment]
{
  "items": [
    {
      "deviceId": "a70bc614-4ca3-41e0-a0ac-88f916d05873",
      "name": "Tag(BLE)",
      "label": "Nøgler",
      "manufacturerName": "Samsung Electronics",
      "presentationId": "IM-SmartTag-BLE",
      "deviceManufacturerCode": "Samsung Electronics",
      "locationId": "99d2db65-0952-4630-950e-09b7632900f3",
      "ownerId": "56f17215-70ca-c5ae-16ae-8b7d11a26cbb",
      "roomId": "167a3865-354d-4e1b-8544-d481a4857b97",
      "components": [
        {
          "id": "main",
          "label": "main",
          "capabilities": [
            {
              "id": "alarm",
              "version": 1
            },
            {
              "id": "tag.tagButton",
              "version": 1
            },
            {
              "id": "audioVolume",
              "version": 1
            },
            {
              "id": "battery",
              "version": 1
            },
            {
              "id": "tag.factoryReset",
              "version": 1
            },
            {
              "id": "tag.e2eEncryption",
              "version": 1
            },
            {
              "id": "tag.tagStatus",
              "version": 1
            },
            {
              "id": "geolocation",
              "version": 1
            },
            {
              "id": "geofence",
              "version": 1
            },
            {
              "id": "tag.updatedInfo",
              "version": 1
            },
            {
              "id": "tag.searchingStatus",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "BluetoothTracker",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2021-09-10T14:44:41.094Z",
      "bleD2D": {
        "encryptionKey": "VDOsWYdgQHyS-EBvkvQ09XFKIFTCMzff_-1H211vqAg=",
        "cipher": "AES_128-CBC-PKCS7Padding",
        "identifier": "C2DDBBC39E04",
        "configurationVersion": "2.0",
        "configurationUrl": "https://apis.samsungiotcloud.com/v1/miniature/profile/c02e8c67-605d-44fc-89c6-2b7026b30b59",
        "metadata": {
          "regionCode": 11,
          "privacyIdPoolSize": 1000,
          "privacyIdSeed": "AAAAAAAGGv0=",
          "privacyIdInitialVector": "xH0mPgY8RtWNPvCLu9rZJw==",
          "numAllowableConnections": 2,
          "firmware": {
            "version": "01.01.26",
            "updateTime": 1634276097000,
            "latestFirmware": {
              "id": 561,
              "version": "1.01.26",
              "data": {
                "checksum": "9B3A",
                "size": "182952",
                "supportedVersion": "0.4.7"
              }
            }
          },
          "currentServerTime": 1639410973,
          "searchingStatus": "stop",
          "lastKnownConnection": {
            "updated": 1639409738,
            "connectedUser": {
              "id": "dxnj1t7crj",
              "name": "Eva Justesen"
            },
            "connectedDevice": {
              "id": "5a328e31-384a-3333-8d20-cbb38c78ec1b",
              "name": "Evas Note20"
            },
            "d2dStatus": "gattConnected",
            "nearby": true,
            "onDemand": false
          },
          "lostMessage": {
            "enabled": false,
            "type": "PREDEFINED"
          },
          "e2eEncryption": {
            "enabled": false
          },
          "geolocationStorage": {
            "recentDataOnly": true
          },
          "timer": 1639373388,
          "category": {
            "id": 100
          },
          "remoteRing": {
            "enabled": true,
            "targetId": "IMEI:357879701866267",
            "targetName": "Evas Note20"
          },
          "onboardedBy": {
            "saGuid": "dxnj1t7crj"
          },
          "shareable": {
            "enabled": false
          },
          "battery": {
            "level": "FULL",
            "updated": 1639409738
          },
          "agingCounter": {
            "status": "VALID",
            "updated": 1639373388
          },
          "vendor": {
            "mnId": "0AFD",
            "setupId": "430"

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
OK, some things to investigate further there. Could you go to the "Send Command" tab (in Configure App on the phone or https://tools.developer.homey.app/tools/app-settings > SmartThings Hub in a web browser).
Then enter (copy / paste) each of these commands into the edit box that is just above the Send Button and copy the returned data for each to the reply:

devices/a70bc614-4ca3-41e0-a0ac-88f916d05873/components/main/capabilities/tag.tagButton/status

devices/a70bc614-4ca3-41e0-a0ac-88f916d05873/components/main/capabilities/tag.tagStatus/status

devices/a70bc614-4ca3-41e0-a0ac-88f916d05873/components/main/capabilities/geolocation/status

devices/a70bc614-4ca3-41e0-a0ac-88f916d05873/components/main/capabilities/geofence/status

devices/a70bc614-4ca3-41e0-a0ac-88f916d05873/components/main/capabilities/tag.searchingStatus/status

**Comment by Corneliusmor** [comment]
Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
Sorry, I don't understand your last message.

**Comment by Corneliusmor** [comment]
Its what ypu asked me to do  I took screenshots of the message i got from doing it.

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
But it is just a link to download Outlook for Android!

**Comment by Corneliusmor** [comment]
Check the attachments

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
The link just takes me to the Outlook app in the Google play store. From there I open Outlook, which is already on my phone, but I get nothing else.

**Comment by Corneliusmor** [comment]
There are 5 attagements. Dont open link  oven aftagemwnt

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
Sorry, but I am not seeing any attachments.

**Comment by Corneliusmor** [comment]
Sorry i cant help you then

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
Unfortunately, without that information I can't see what the data format is of those capabilities so I don't know how to decode the information.
Could you copy and past the text from the list into the reply?

**Comment by robertklep** [comment]
@Corneliusmor please go to https://github.com/AdyRock/com.smartthings/issues/23 with a browser and post your attachments there instead of replying to e-mail messages, Github doesn't support attachments in e-mails.

**Comment by Corneliusmor** [comment]
![Screenshot_20211213-182849_Homey](https://user-images.githubusercontent.com/96069385/146003041-39577fe0-7a9d-498e-9b0e-4e320f17fa5c.jpg)



Same answer in every

**Comment by AdyRock** [comment]
Ah, The place to enter the request text is just above the buttons. If you tap on the line you should see the cursor appear.
The Athom default css doesn't make text boxes stand out well unfortunately so I will need to adapt that.

**Comment by Corneliusmor** [comment]
![Screenshot_20211214-141332_Homey](https://user-images.githubusercontent.com/96069385/146004995-2f8dee7d-ce45-44b9-8c45-34e58baed993.jpg)

**Comment by Corneliusmor** [comment]
![Screenshot_20211214-141313_Homey](https://user-images.githubusercontent.com/96069385/146005035-a77f0573-5699-4556-8363-6b98b647aa69.jpg)

**Comment by Corneliusmor** [comment]
![Screenshot_20211214-141252_Homey](https://user-images.githubusercontent.com/96069385/146005065-00e38454-e24b-46db-8bcf-2739869fd073.jpg)

**Comment by Corneliusmor** [comment]
![Screenshot_20211214-141232_Homey](https://user-images.githubusercontent.com/96069385/146005089-b51f5fea-f5d6-4cc6-9f07-97209092ad19.jpg)

**Comment by Corneliusmor** [comment]
![Screenshot_20211214-141209_Homey](https://user-images.githubusercontent.com/96069385/146005107-fb2dd28e-6769-4bc5-a53c-3f5b8c022ed7.jpg)

**Comment by AdyRock** [comment]
Hmm, that's disappointing as it looks none of those are used.
Now I have looked back at the original table it looks incomplete. was that all there was in the detected devices list or has GitHub truncated the message?
I will try to do some more investigations about tags in SmartThings. 
What tags are you using?
If they are not too expensive and available in the UK I will get one to play with.

**Comment by Corneliusmor** [comment]
I used samsung smarttag. Might be i bought 4 for 65 british pund.

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
Is this the device?
Samsung Galaxy SmartTag Bluetooth Item Finder and Key Finder, 120 m Finding Range, 1 Pack, Black (UK Version) https://www.amazon.co.uk/dp/B08P94RML3/ref=cm_sw_r_apan_glt_fabc_TACYT234F0TRWT0QFFV2

**Comment by Corneliusmor** [comment]
Yes that looks like mine

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
OK, I have ordered one and should be with me tomorrow.

**Comment by AdyRock** [comment]
I have had a play with the SmartTag and it is disappointing.
If I assign actions to the button in the SmartThings phone app then the button press and long press messages to appear in the tag.tagButton status along with the time the button was pressed.
I can't see that anything else is reported so probably not worth adding it.

**Comment by Corneliusmor** [comment]
That is dissapointing.  Was hoping my son could use it to lock and open the alarm.

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdyRock** [comment]
It's strange that actions have to be assigned to the button in SmartThings to get any notification in the API.
I guess the actions could be simple notifications sent to a phone.
In the Homey app I would need to check for the time change to detect if it is a new button press so it would be a special case and might need to be added as a dedicated device.
I will have another look this evening.
