### ISSUE TITLE
How to connect to samsung AC whitout smartthings hub ? 

### ISSUE THREAD

**Issue by Sjonne78** [AdyRock/com.smartthings#25]
Hello everyone

I'm very new to this smart home world and brand new to homey ... so maybe I'm asking stupid, but hope you will help anyway.
I do not have a smartthings hub, but I have a smarttings cloud account where I can control my AC ... can I somehow access my
cloud account via homey so I can control my AC with homey?
Or is there a better way?

**Comment by AdyRock** [comment]
My SmartThings app might work with it or I might be able to help. 
If you install the app from the Homey Community Store and follow the instructions to login to your account. Then try to add a device and see if it finds it. 
The app works on generic capabilities so will try to add various devices. 

https://store.homey.community/app/com.smartthings

**Comment by Sjonne78** [comment]
Hi AdyRock

Thanks for your quick reply

I followed your indtructions but now I stuck "you will need to enter it in the “Configure app” page of this app"
I do not know where to find the Configure app ”page of this app

Maybe I'm in deep water because I'm new to it. But I really want it to work.

Hope you can help me

**Comment by Sjonne78** [comment]
Hello again

I figured out what to do .... thank you so much.

I'm so happy to be able to get in touch with my AC through homey.
What a great job you have done. thanks again
