### ISSUE TITLE
[feature request] add input source choice of soundbar

### ISSUE THREAD

**Issue by B3rt** [AdyRock/com.smartthings#26]
Is it possible to add the option to select the input source using flow cards?
The device is listed and imported in Homey, in the smartthings app you can set the input source: d.in, hdmi1, hdmi2, wifi, bt etc
When i open the device (which is created) in Homey i can change the volume and power it on/off but (for me) the most important settings to change the input source is sadly not possible.

I hope this can be added.

The device itself is a Samsung HQ-950A soundbar

**Comment by AdyRock** [comment]
Could you go through the "how to provide information...." section so I can see what information it provides.

**Comment by B3rt** [comment]
i read that part but not sure where to find these options or info, that is not mentioned..

Is this in the smarttings app or in the homey app or maybe somewhere else?
When i try the homey app it display no device found (this is correct, the device itself is already added the in homey).

**Comment by AdyRock** [comment]
It's in Homey. So once you get to the no devices found part, close the add device wizard and the follow the reset of the instructions for the More > Apps > SmartThings > Configure App, etc. 
The More button is in the bottom right corner of the Homey phone app. It's not available in the web app.

**Comment by B3rt** [comment]
{
  "items": [
    {
      "deviceId": "144c1754-899d-8abb-4e4a-44b2dee7517f",
      "name": "Samsung Soundbar Q950A",
      "label": "Samsung Soundbar Q950A",
      "manufacturerName": "Samsung Electronics",
      "presentationId": "VD-NetworkAudio-002S",
      "deviceManufacturerCode": "Samsung Electronics",
      "locationId": "8833e7eb-cc2a-406c-9539-7594fed83230",
      "ownerId": "efd06559-2843-e3de-9f1b-08a9543f4b53",
      "roomId": "359ddc92-600d-4157-bee4-7d51a6231524",
      "deviceTypeName": "Samsung OCF Network Audio Player",
      "components": [
        {
          "id": "main",
          "label": "main",
          "capabilities": [
            {
              "id": "ocf",
              "version": 1
            },
            {
              "id": "execute",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "switch",
              "version": 1
            },
            {
              "id": "audioVolume",
              "version": 1
            },
            {
              "id": "audioMute",
              "version": 1
            },
            {
              "id": "audioTrackData",
              "version": 1
            },
            {
              "id": "mediaInputSource",
              "version": 1
            },
            {
              "id": "mediaPlayback",
              "version": 1
            },
            {
              "id": "audioNotification",
              "version": 1
            },
            {
              "id": "samsungvd.soundFrom",
              "version": 1
            },
            {
              "id": "samsungvd.groupInfo",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "NetworkAudio",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2022-01-25T17:35:19.424Z",
      "type": "OCF",
      "restrictionTier": 0
    }
  ],
  "_links": {}
}

**Comment by AdyRock** [comment]
I have published an update that should display the input source in the tile details.
You will need to remove the old device and add it again to get the new capability.
Once you have it updated and can see the new status, could you then switch on the log (located on the next tab along from the device log you sent before and the tick should be blue when it is on). Wait for the list to populate and then send me a copy of the contents. Now I have added the source input status, the log should show me what is retrieved for that parameter. Once I can see the format of the data I will hopefully know how to handle it so it can be set.

**Comment by B3rt** [comment]
i removed the device and readded it, but there is no change, the options are identical as before i removed it.

{
  "items": [
    {
      "deviceId": "144c1754-899d-8abb-4e4a-44b2dee7517f",
      "name": "Samsung Soundbar Q950A",
      "label": "Samsung Soundbar Q950A",
      "manufacturerName": "Samsung Electronics",
      "presentationId": "VD-NetworkAudio-002S",
      "deviceManufacturerCode": "Samsung Electronics",
      "locationId": "8833e7eb-cc2a-406c-9539-7594fed83230",
      "ownerId": "efd06559-2843-e3de-9f1b-08a9543f4b53",
      "roomId": "359ddc92-600d-4157-bee4-7d51a6231524",
      "deviceTypeName": "Samsung OCF Network Audio Player",
      "components": [
        {
          "id": "main",
          "label": "main",
          "capabilities": [
            {
              "id": "ocf",
              "version": 1
            },
            {
              "id": "execute",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "switch",
              "version": 1
            },
            {
              "id": "audioVolume",
              "version": 1
            },
            {
              "id": "audioMute",
              "version": 1
            },
            {
              "id": "audioTrackData",
              "version": 1
            },
            {
              "id": "mediaInputSource",
              "version": 1
            },
            {
              "id": "mediaPlayback",
              "version": 1
            },
            {
              "id": "audioNotification",
              "version": 1
            },
            {
              "id": "samsungvd.soundFrom",
              "version": 1
            },
            {
              "id": "samsungvd.groupInfo",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "NetworkAudio",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2022-01-26T23:16:14.749Z",
      "type": "OCF",
      "restrictionTier": 0
    }
  ],
  "_links": {}
}

**Comment by B3rt** [comment]
hmmm on the store it mention the current version is 1.0.9 but in the homey app is listed as 1.0.8
It seems there is no option to update this manually, when i click install nothing happens, also i cannot find any update function.
On the timeline it displays when i press install:
The Homey Community Store updated SmartThings Hub from v1.0.8 to v1.0.8
(and yes 1.0.9 is selected and displayed in the store)

Must i complete remove the app and then install the whole app again or did i miss somewhere the update function?

**Comment by B3rt** [comment]
I do have an other request.
Is it possible to add also the sound mode (available modes are: standard, surround, game pro, adaptive sound)

**Comment by AdyRock** [comment]
OK, I have published it again and hopefully it should install the correct version this time.
In this version I have taken a chance and the Input Source should now be a list in the device. It contains all possible options so not all of them will apply to your device, but Homey doesn't allow for dynamic lists.
I have also added the samsungvd.soundFrom as a status to see if that is the Sound Mode. If it's not then I can't see any other option to use for that.

**Comment by B3rt** [comment]
Can you explain to me how i should update this?

The app in homey is on v1.0.8 and it seems it does not 'auto update' itself.
In the store it is now on v1.0.10, the only option i found is to press install button again. 
Then it displays it will be installed..
When i then look in the Homey APP this message appears on the timeline and nothing happens:
The Homey Community Store updated SmartThings Hub from v1.0.8 to v1.0.8
4 minuten geleden

It does not update, what do i wrong here?
Should i remove the app first and then reinstall it?

**Comment by AdyRock** [comment]
I'm not sure why the store is not updating to the correct version. I think removing the app and reinstalling is a good idea.

**Comment by B3rt** [comment]
Don't know what went wrong but even removing had no effect, after remove it did not install anymore.

I rebooted Homey and then everything worked again and i could install the app and add the device again.

But sadly the changes produce an error in the homey app.
![Screenshot_20220127-130802_Homey](https://user-images.githubusercontent.com/720614/151356240-330d290c-6e17-49a1-88ed-8e4a19e0d57b.jpg)

Also the displayed list of input sources does not match the actual list in the smartthing app.

Sadly the sound mode also does nothing, there is nothing to choose etc.

Using flow cards to change something is also not possible because there are no flow card options (so no input source of sound flow cards) available to use.

**Comment by B3rt** [comment]
here the log:

mestamp": "2022-01-27T10:33:01.164Z"
  },
  "detailName": {
    "value": "External Device",
    "timestamp": "2022-01-27T10:33:01.164Z"
  }
}
* getDeviceValues error: Cannot read property 'value' of undefined
* !!!!!! Polling finished
* Next Interval = 5000
* !!!!!! Polling started
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/switch/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/switch/status
Result: {
  "switch": {
    "value": "on",
    "timestamp": "2022-01-27T12:16:51.177Z"
  }
}
* Set Capability: onoff - Value: true
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioVolume/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioVolume/status
Result: {
  "volume": {
    "value": 6,
    "unit": "%",
    "timestamp": "2022-01-27T10:56:33.018Z"
  }
}
* Set Capability: volume_set - Value: 0.06
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioMute/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioMute/status
Result: {
  "mute": {
    "value": "unmuted",
    "timestamp": "2022-01-27T10:32:59.146Z"
  }
}
* getDeviceValues error: Cannot read property 'value' of undefined
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/mediaInputSource/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/mediaInputSource/status
Result: {
  "supportedInputSources": {
    "value": [
      "digital",
      "HDMI1",
      "bluetooth",
      "HDMI2",
      "wifi"
    ],
    "timestamp": "2022-01-26T23:16:16.155Z"
  },
  "inputSource": {
    "value": "digital",
    "timestamp": "2022-01-27T00:26:17.652Z"
  }
}
* getDeviceValues error: Cannot read property 'value' of undefined
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/samsungvd.soundFrom/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/samsungvd.soundFrom/status
Result: {
  "mode": {
    "value": 24,
    "timestamp": "2022-01-27T10:33:01.164Z"
  },
  "detailName": {
    "value": "External Device",
    "timestamp": "2022-01-27T10:33:01.164Z"
  }

**Comment by AdyRock** [comment]
OK, Another new version is in the store. This should have the correct list of sources and an action card to operate it.
I have also removed the 'sound mode' as it is obviously not the correct parameter and as there are no other candidates I have to conclude that it is not made public.

**Comment by B3rt** [comment]
i updated the version, the inputs are now correct (and sound is gone), but sadly changing the input still gives an error (and do not work)

Here is the log:
* !!!!!! Polling started
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/switch/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/switch/status
Result: {
  "switch": {
    "value": "on",
    "timestamp": "2022-01-27T12:16:51.177Z"
  }
}
* Set Capability: onoff - Value: true
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioVolume/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioVolume/status
Result: {
  "volume": {
    "value": 9,
    "unit": "%",
    "timestamp": "2022-01-27T19:32:51.847Z"
  }
}
* Set Capability: volume_set - Value: 0.09
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioMute/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioMute/status
Result: {
  "mute": {
    "value": "unmuted",
    "timestamp": "2022-01-27T10:32:59.146Z"
  }
}
* getDeviceValues error: Cannot read property 'value' of undefined
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/mediaInputSource/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/mediaInputSource/status
Result: {
  "supportedInputSources": {
    "value": [
      "digital",
      "HDMI1",
      "bluetooth",
      "HDMI2",
      "wifi"
    ],
    "timestamp": "2022-01-26T23:16:16.155Z"
  },
  "inputSource": {
    "value": "digital",
    "timestamp": "2022-01-27T00:26:17.652Z"
  }
}
* Set Capability: media_input_source - Value: digital
* Capability Map entry NOT found for: sound_mode
* !!!!!! Polling finished
* Next Interval = 5000
* PostURL url: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/commands
* PostUrl body: {"commands":[{"component":"main","capability":"inputSource","command":"setInputSource","arguments":["bluetooth"]}]}
* HTTPS Error: 422: 
* Samsung Soundbar Q950A: main onCapabilityMediaInputSource Error undefined
* !!!!!! Polling started
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/switch/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/switch/status
Result: {
  "switch": {
    "value": "on",
    "timestamp": "2022-01-27T12:16:51.177Z"
  }
}
* Set Capability: onoff - Value: true
* devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioVolume/status
* Get device: devices/144c1754-899d-8abb-4e4a-44b2dee7517f/components/main/capabilities/audioVolume/status
Result: {
  "volume": {
    "value": 9,
    "unit": "%",
    "timestamp": "2022-01-27T19:32:51.847Z"
  }
}
* Set Capability: volume_set - Value: 0.09
*

**Comment by AdyRock** [comment]
Ah, sorry, looks like I picked "InputSource" instead of "mediaInputSource" when sending the value.
The new version should fix that 🤞🤞.

**Comment by B3rt** [comment]
Yes, seems to work now.

Thx!

Only the update function does not work properly, but i think this has nothing todo with your app but with the app of the community store.
Again it did not update when i pressed install, it tried again to install the same (old) version.
After restarting your app and the store app in Homey it updated when i pressed install in the store.
