### ISSUE TITLE
Dryer status trigger issue

### ISSUE THREAD

**Issue by mvervoorn** [AdyRock/com.smartthings#29]
Hi Ady,

I recently download and installed your app for my new Samsung dryer. It perfectly included the device in home and I'm able to control everything like dryer programs, starting, stopping etc.

However there is one flow trigger that does not work. That is the trigger on the dryer status (running or stopped) I would like to send a message when the dryer is running on or stopped. It seems this never triggers. Maybe because in the main icon it shows as run, pause, stop, and in the flow it's called running, stopped. not sure. Could you have a look at this?

I have some screenshots below

![image](https://user-images.githubusercontent.com/23385039/155899995-a01af146-781e-4df1-a9de-e309a586a8dd.png)
![image](https://user-images.githubusercontent.com/23385039/155900070-911d6655-2fea-44cd-8322-abf19015208e.png)
![image](https://user-images.githubusercontent.com/23385039/155900048-2c833e47-eac9-43ba-b5fa-00e4c190d6ce.png)

Thanks a lot!

Regards,

Maarten

**Comment by AdyRock** [comment]
Hi, I was just going through the topics to have a tidy up and noticed I hadn't got back to you about this. My sincere apologies for that.
The issue should be fixed in the latest version so I will close the topic, but please get back to me if you still have problems with it.
