### ISSUE TITLE
Fibaro dimmer only identified as outlet

### ISSUE THREAD

**Issue by AndKjell** [AdyRock/com.smartthings#30]
This is a great app and works for most of my devices.
However, my Fibaro dimmers are only showing up with on/off and not as dimmable.

Here is one of them:
    {
      "deviceId": "c44693cf-b85b-40dc-8d99-7c7fc8effc21",
      "name": "Fibaro Dimmer Switch",
      "label": "Living Room Ceiling Lamp",
      "manufacturerName": "SmartThings",
      "presentationId": "generic-dimmer-power-energy",
      "deviceManufacturerCode": "010F-0102-1000",
      "locationId": "bbae6ead-98f1-4419-8418-c5f402e7eaa3",
      "roomId": "ec2a1021-e00c-429a-b08a-585b1fbe7b10",
      "deviceTypeId": "7331de54-dd07-4ce1-9cde-f733a56265ce",
      "deviceTypeName": "Fibaro Dimmer 2 ZW5",
      "deviceNetworkType": "ZWAVE",
      "components": [
        {
          "id": "main",
          "label": "Living Room Ceiling Lamp",
          "capabilities": [
            {
              "id": "switch",
              "version": 1
            },
            {
              "id": "configuration",
              "version": 1
            },
            {
              "id": "switchLevel",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "energyMeter",
              "version": 1
            },
            {
              "id": "powerMeter",
              "version": 1
            },
            {
              "id": "healthCheck",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Switch",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2020-11-11T10:13:58Z",
      "parentDeviceId": "c83fb016-9ae7-4841-aeed-bcfa964b55d4",
      "dth": {
        "completedSetup": true,
        "deviceNetworkType": "ZWAVE",
        "deviceTypeId": "7331de54-dd07-4ce1-9cde-f733a56265ce",
        "deviceTypeName": "Fibaro Dimmer 2 ZW5",
        "executingLocally": true,
        "hubId": "c83fb016-9ae7-4841-aeed-bcfa964b55d4",
        "networkSecurityLevel": "ZWAVE_S0_LEGACY"
      },
      "type": "DTH",
      "restrictionTier": 0,
      "allowed": []
    },

**Comment by AdyRock** [comment]
I'm surprised it's not giving the Dim option as it should find the "id": "switchLevel" and add the capability. However, now that I have a dimmable bulb I can see it is not working for some reason.
I will investigate and get back to you.

**Comment by AdyRock** [comment]
I have published a new version that should fix the Dim issue

**Comment by AndKjell** [comment]
I have a message "The Homey Community Store updated SmartThings Hub from v1.0.15 to v1.0.15". I would have expected a version bump. Tried to remove and re-add one of my dimmers, but it still only shows as on/off and nothing that has to do with dimming. Is there anything else I have to do for the new version to be downloaded to Homey?

**Comment by AdyRock** [comment]
Could you try restarting Homey. I have heard of other similar issues with app updates and that sometimes fixes it.

**Comment by AndKjell** [comment]
That didn't help so I uninstalled and reinstalled the app. The devices are now identified as a lamp and I can dim them. Thanks a lot.

**Comment by AndKjell** [comment]
Works as expected.
