### ISSUE TITLE
SmartThing button does not have any actions

### ISSUE THREAD

**Issue by AndKjell** [AdyRock/com.smartthings#31]
Hi,
I have a SmartThing button  that can measure temperature as well as being a normal button. However, in flows it only shows up with temperature actions. I expected it to also show up with actions "Pressed", "Double pressed", and "Held".

 {
      "deviceId": "be8c1e0e-dbeb-41c1-a20a-1d1d57bc7f7a",
      "name": "one-button-temp-battery",
      "label": "Balcony Button",
      "manufacturerName": "SmartThingsCommunity",
      "presentationId": "b78f59cb-0fb4-39d6-b925-7d15659d539f",
      "deviceManufacturerCode": "Samjin",
      "locationId": "bbae6ead-98f1-4419-8418-c5f402e7eaa3",
      "roomId": "5b88a3f1-ef74-49c4-a1cd-ef647a0e4260",
      "components": [
        {
          "id": "main",
          "label": "main",
          "capabilities": [
            {
              "id": "battery",
              "version": 1
            },
            {
              "id": "button",
              "version": 1
            },
            {
              "id": "firmwareUpdate",
              "version": 1
            },
            {
              "id": "refresh",
              "version": 1
            },
            {
              "id": "temperatureMeasurement",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "RemoteController",
              "categoryType": "manufacturer"
            }
          ]
        }
      ],
      "createTime": "2022-06-05T12:22:03.193Z",
      "parentDeviceId": "c83fb016-9ae7-4841-aeed-bcfa964b55d4",
      "profile": {
        "id": "5522dbd7-fdd4-3e12-a83f-08102e8d7f5e"
      },
      "zigbee": {
        "eui": "286D97000107C659",
        "networkId": "EE41",
        "driverId": "3fb97b6c-f481-441b-a14e-f270d738764e",
        "executingLocally": true,
        "hubId": "c83fb016-9ae7-4841-aeed-bcfa964b55d4",
        "provisioningState": "PROVISIONED"
      },
      "type": "ZIGBEE",
      "restrictionTier": 0,
      "allowed": []
    },

**Comment by AdyRock** [comment]
Can you try the new version to see if that works.
Remember, the app polls for updates so the response will probably be a bit slow.

**Comment by AndKjell** [comment]
Halfway there. The device is now reported with a Button state on the device and it shows these correctly. But there is no card I can use to automate it. For example, I have another similar device from Aeotec and there I have a card "Button is (action)". The Button state also looks like it is permanent so I can see "pushed - 4 minutes ago". Even if I had a card, would it trigger again when the state is still the same? It does not look like it. The state is still "Pushed - 5 minutes ago" when I push the button a second time. So I guess it will be hard to create an on/off flow.

**Comment by AdyRock** [comment]
Could you enable the log from https://tools.developer.homey.app/tools/app-settings, select the Log tab and turn on the LOG ENABLED option so it has a blue tick.
When the logging is on, press the button, wait 35 seconds, then double press the button, wait 35 seconds, etc. Once you have done that copy the log and then send it to me (a d y at r o c k a l l . p l u s . c o m)

I forgot to add the new capability to the trigger card filter so that will be in the next update.

**Comment by AdyRock** [comment]
I have published a new version, sorry it took so long.
There is now a timestamp shown for the button press event and when that changes it will trigger the button pressed flow card.

I could see which devices are causing the errors so I have added Send Log buttons to the log pages to make it easier to provide the information. If you could send the detected devices log and the information log after it has fetched the information, then hopefully I can tie the errors to devices.

**Comment by AndKjell** [comment]
Unfortunately I still do no not see any actions on the button itself when I try to create a flow. Still only battery and temperature. Tried to remove and readd the button, but that didn't help.
I've sent the other log as requested.

**Comment by AdyRock** [comment]
I have published a new version.
It seems there is a bug in the API with filtering flows cards on multiple capabilities. So I have added a new flow card for the button.
Also now shows the update time.
Unfortunately you will need to remove and re-add the button.

**Comment by AndKjell** [comment]
Now it works! Thank you.
The only thing is that the tag on the device is called "button state" but on the card "button status". But you can get it to work as expected by using the tag on the device.

**Comment by AndKjell** [comment]
Works as expected.
