### ISSUE TITLE
Vision sensor

### ISSUE THREAD

**Issue by ganza73** [AdyRock/com.smartthings#4]
just testet the SmartThings visions sensor, has just on/off capabilities in Homey, so function not working, had to try :)

**Comment by AdyRock** [comment]
After adding the device can you copy the contents of the device tab in the app configuration page and paste it here?
That will let me know what to pickup for the capabilities.

**Comment by ganza73** [comment]
"     "deviceNetworkType": "UNKNOWN",
      "components": [
        {
          "id": "main",
          "capabilities": [
            {
              "id": "switch",
              "version": 1
            },
            {
              "id": "motionSensor",
              "version": 1
            },
            {
              "id": "imageCapture",
              "version": 1
            },
            {
              "id": "signalStrength",
              "version": 1
            },
            {
              "id": "healthCheck",
              "version": 1
            },
            {
              "id": "videoCapture",
              "version": 1
            },
            {
              "id": "videoStream",
              "version": 1
            },
            {
              "id": "videoClips",
              "version": 1
            },
            {
              "id": "objectDetection",
              "version": 1
            },
            {
              "id": "activitySensor",
              "version": 1
            }
          ],
          "categories": [
            {
              "name": "Camera"
            }
          ]
        }
      ],
      "dth": {
        "
      },
      "type": "DTH",
      "restrictionTier": 0
    }
  ],
  "_links": {}
}

**Comment by AdyRock** [comment]
Hi,
It looks like I should be able to support the motion sensor and possibly the object detection and activity sensor.
If that sound promising then can you turn on the logging feature in the app configuration, wait for the data to be received, preferably with and without motion active, so I can see what the actual data format of these are?
Homey can't support a video stream so no hope there but depending on the image format, etc, I might be able to add a snapshot.
