### ISSUE TITLE
Samsung washing machine not showing electric power: always 0 watt.

### ISSUE THREAD

**Issue by thebossbe** [AdyRock/com.smartthings#47]
Hi all,
I'm using a Homey Pro 2023 in combination with the Samsung Smartthings app and a Samsung Washing Machine. In Homey, I see the washing machine, every possibility, so, nice! Works fine.
Only thing is: when the machine is active, the power remains at 0 watt. It never changes. Also in the Homey statistics: flat line, always 0 watt.
Is this anything known or already reported? I didn't find anything similar in the other posts...

Thanks,
Frederik.

**Comment by AdyRock** [comment]
That is a known issue. The Api doesn't return the data, even though it says it supports it.

**Comment by thebossbe** [comment]
That explains everything... Thanks!
