### ISSUE TITLE
Can't add samsung Q8 tv

### ISSUE THREAD

**Issue by Michaelv1984** [AdyRock/com.smartthings#5]
Hi,
I can't add my Samsung Q8 TV. I created a token and if I add the TV I see the name of the TV. But if I add the TV it says [invalid class].
What did I do wrong? 
![Screenshot_20200917-141812_Homey](https://user-images.githubusercontent.com/71445229/93473794-bc1ecd80-f8f6-11ea-8216-945a1d00b5b5.jpg)

**Comment by adrianipopescu** [comment]
Hey Adrian,

Spamming you here in order to not open up another ticket, having the same issue as the person above. The auth code seems good, the devices get listed, it's just it throws an invalid class error.

Tried restarting the homey app, same thing.

Logs just show [Object object] and no specific error.

After abusing your code by just running the getDevices method in isolation, I got the following output:
`[
  {
    "name": "Main TV: main",
    "icon": "television.svg",
    "class": "TV",
    "capabilities": [
      "onoff",
      "volume_set",
      "volume_down",
      "volume_up",
      "volume_mute",
      "channel_down",
      "channel_up"
    ],
    "data": {
      "id": "db4f2fde-af6e-4094-8408-b6d69ed40ae5",
      "component": "main"
    }
  }
]`

Tried calling the api for the mappable capabilities in the capabilityMap1 array inside the driver, using the configured token and I obtain valid statuses.

Any quick ideas on what to check?

**Comment by AdyRock** [comment]
Hmm, that's embarrassing, I don't remember seeing this issue before. I always try to reply as quickly as possible and I see this one has been live since September last year.

Any way, hopefully fixed now. It was simple (stupid) mistake where I had set the class to 'TV' instead of 'tv'.
I have checked in the changes and published to the HCS so the choice is yours  how to get it.

**Comment by adrianipopescu** [comment]
Can confirm, works now. 

Many thanks!

**Comment by Michaelv1984** [comment]
Thanks for replying. I was already forgotten I placed this question 😅.
I will try this weekend if the solution works. 
Thanks! 😀

**Comment by Michaelv1984** [comment]
Hey it now works! Thanks!
I can finally add my Samsung Q8 TV. 

I do have another question. 
Is it possible to add the option/key ambient mode in homey?

**Comment by AdyRock** [comment]
Can you send me the log from the app configuration, log tab. 
So turn on the logging, wait for the list to populate and then copy it and paste on here.
Hopefully it will show the required settings so I can add it to the app.

**Comment by Michaelv1984** [comment]
a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/audioVolume/status
* {
  "volume": {
    "value": 0,
    "unit": "%",
    "timestamp": "2020-12-22T15:28:09.657Z"
  }
}
* Set Capability: volume_set - Value: 0
* Capability Map entry NOT found for: volume_down
* Capability Map entry NOT found for: volume_up
* devices/7f7a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/audioMute/status
* {
  "mute": {
    "value": "unmuted",
    "timestamp": "2020-12-22T15:28:09.657Z"
  }
}
* getDeviceValues error: {}
* Capability Map entry NOT found for: channel_down
* Capability Map entry NOT found for: channel_up
* Next Interval = 5000
* devices/7f7a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/switch/status
* {
  "switch": {
    "value": "off",
    "timestamp": "2021-02-01T05:53:31.885Z"
  }
}
* Set Capability: onoff - Value: false
* devices/7f7a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/audioVolume/status
* {
  "volume": {
    "value": 0,
    "unit": "%",
    "timestamp": "2020-12-22T15:28:09.657Z"
  }
}
* Set Capability: volume_set - Value: 0
* Capability Map entry NOT found for: volume_down
* Capability Map entry NOT found for: volume_up
* devices/7f7a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/audioMute/status
* {
  "mute": {
    "value": "unmuted",
    "timestamp": "2020-12-22T15:28:09.657Z"
  }
}
* getDeviceValues error: {}
* Capability Map entry NOT found for: channel_down
* Capability Map entry NOT found for: channel_up
* Next Interval = 5000
* devices/7f7a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/switch/status
* {
  "switch": {
    "value": "off",
    "timestamp": "2021-02-01T05:53:31.885Z"
  }
}
* Set Capability: onoff - Value: false
* devices/7f7a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/audioVolume/status
* {
  "volume": {
    "value": 0,
    "unit": "%",
    "timestamp": "2020-12-22T15:28:09.657Z"
  }
}
* Set Capability: volume_set - Value: 0
* Capability Map entry NOT found for: volume_down
* Capability Map entry NOT found for: volume_up
* devices/7f7a105b-4e9a-4f05-96f6-e3154937f61d/components/main/capabilities/audioMute/status
* {
  "mute": {
    "value": "unmuted",
    "timestamp": "2020-12-22T15:28:09.657Z"
  }
}
* getDeviceValues error: {}
* Capability Map entry NOT found for: channel_down
* Capability Map entry NOT found for: channel_up

**Comment by Michaelv1984** [comment]
Is this the log that you mean?

**Comment by AdyRock** [comment]
OK, that has got the ID of the TV, so next:
On the app Configuration page there is a tab called Send Command. On this tab you can enter commands to send to your SmartThings account. The command is entered just below the text that says For debug use only.
Could you type / paste the following command into the Send Command tab:

/devices/a105b-4e9a-4f05-96f6-e3154937f61d/status

Where a105b-4e9a-4f05-96f6-e3154937f61d is the id of your TV..

Once the the list has populated, can you send it to me.
That should show all the capabilities of the TV. In the older versions the log used to list everything but I keep forgetting that I optimized it to only fetch the mapped in capabilities.

Although, the log does has something for me to look into as well with the "Capability Map entry NOT found ..." messages.

**Comment by Michaelv1984** [comment]
I tried what you said but this is what get when sending the command:
![Screenshot_20210201-105734_Homey](https://user-images.githubusercontent.com/71445229/106443131-749b7700-647c-11eb-9f4a-1e6eb9517a0c.jpg)

**Comment by Michaelv1984** [comment]
I noticed the volume up button of the Samsung TV in the homey app is also not working

**Comment by AdyRock** [comment]
Typical, I copied the id from the first line of the log and that had the start missing. can you replace the id with 7f7a105b-4e9a-4f05-96f6-e3154937f61d and try again.

I think the volume up button is the issue reported in the log. It appears I have missed out volume_up, volume_down, channel_up and channel_down from one of my tables.
Hopefully the log should also tell me the appropriate ST names for those as well.

**Comment by Michaelv1984** [comment]
It worked! 


{
  "components": {
    "main": {
      "mediaPlayback": {
        "supportedPlaybackCommands": {
          "value": [
            "play",
            "pause",
            "stop",
            "fastForward",
            "rewind"
          ],
          "timestamp": "2020-05-06T05:03:16.152Z"
        },
        "playbackStatus": {
          "value": null,
          "timestamp": "2020-09-02T07:57:29.145Z"
        }
      },
      "audioVolume": {
        "volume": {
          "value": 0,
          "unit": "%",
          "timestamp": "2020-12-22T15:28:09.657Z"
        }
      },
      "samsungvd.supportsPowerOnByOcf": {
        "supportsPowerOnByOcf": {
          "value": "true",
          "timestamp": "2020-11-02T08:44:49.219Z"
        }
      },
      "samsungvd.mediaInputSource": {
        "supportedInputSourcesMap": {
          "value": [
            {
              "id": "dtv",
              "name": "Tv"
            },
            {
              "id": "HDMI4",
              "name": "Sonos Arc"
            }
          ],
          "timestamp": "2021-01-16T07:46:23.748Z"
        },
        "inputSource": {
          "value": "digitalTv",
          "timestamp": "2021-01-22T13:02:43.707Z"
        }
      },
      "mediaInputSource": {
        "supportedInputSources": {
          "value": [
            "digitalTv",
            "HDMI4"
          ],
          "timestamp": "2021-01-16T22:03:09.561Z"
        },
        "inputSource": {
          "value": "digitalTv",
          "timestamp": "2021-01-22T13:02:43.707Z"
        }
      },
      "custom.tvsearch": {},
      "samsungvd.ambient": {},
      "refresh": {},
      "custom.error": {
        "error": {
          "value": null,
          "timestamp": "2020-09-02T07:29:07.381Z"
        }
      },
      "execute": {
        "data": {
          "value": null,
          "data": {},
          "timestamp": "2020-09-02T07:29:07.679Z"
        }
      },
      "switch": {
        "switch": {
          "value": "on",
          "timestamp": "2021-02-01T10:05:39.369Z"
        }
      },
      "tvChannel": {
        "tvChannel": {
          "value": "",
          "timestamp": "2020-08-15T13:40:54.998Z"
        },
        "tvChannelName": {
          "value": "qvVcLChmPo.NPO",
          "timestamp": "2021-01-16T22:03:09.464Z"
        }
      },
      "ocf": {
        "st": {
          "value": "2020-05-05T08:49:26Z",
          "timestamp": "2020-05-06T05:03:16.197Z"
        },
        "mndt": {
          "value": "2018-01-01",
          "timestamp": "2020-05-06T05:03:16.106Z"
        },
        "mnfv": {
          "value": "T-KTM2DEUC-1310.4",
          "timestamp": "2020-12-22T15:28:06.111Z"
        },
        "mnhw": {
          "value": "0-0",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "di": {
          "value": "7f7a105b-4e9a-4f05-96f6-e3154937f61d",
          "timestamp": "2020-05-06T05:03:16.120Z"
        },
        "mnsl": {
          "value": "http://www.samsung.com/sec/tv/overview/",
          "timestamp": "2020-05-06T05:03:16.126Z"
        },
        "dmv": {
          "value": "res.1.1.0,sh.1.1.0",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "n": {
          "value": "[TV] Samsung Q8 Series (55)",
          "timestamp": "2020-05-06T05:03:16.133Z"
        },
        "mnmo": {
          "value": "QE55Q8FNA",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "vid": {
          "value": "VD-STV_2018_K",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "mnmn": {
          "value": "Samsung Electronics",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "mnml": {
          "value": "http://www.samsung.com",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "mnpv": {
          "value": "Tizen 4.0",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "mnos": {
          "value": "4.1.10",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "pi": {
          "value": "7f7a105b-4e9a-4f05-96f6-e3154937f61d",
          "timestamp": "2020-05-06T05:03:16.137Z"
        },
        "icv": {
          "value": "core.1.1.0",
          "timestamp": "2020-05-06T05:03:16.108Z"
        }
      },
      "custom.picturemode": {
        "pictureMode": {
          "value": "HDR+",
          "timestamp": "2020-12-22T15:28:09.027Z"
        },
        "supportedPictureModes": {
          "value": [
            "HDR+"
          ],
          "timestamp": "2020-12-22T15:28:09.027Z"
        },
        "supportedPictureModesMap": {
          "value": [
            {
              "id": "modeSDRPlus",
              "name": "HDR+"
            }
          ],
          "timestamp": "2020-12-22T15:28:09.027Z"
        }
      },
      "samsungvd.ambientContent": {
        "supportedAmbientApps": {
          "value": [],
          "timestamp": "2021-01-16T22:03:08.492Z"
        }
      },
      "custom.accessibility": {},
      "custom.recording": {},
      "custom.disabledCapabilities": {
        "disabledCapabilities": {
          "value": [
            "samsungvd.ambient",
            "samsungvd.ambientContent"
          ],
          "timestamp": "2021-01-16T22:03:09.546Z"
        }
      },
      "samsungvd.ambient18": {},
      "custom.soundmode": {
        "supportedSoundModesMap": {
          "value": [
            {
              "id": "modeStandard",
              "name": "Standaard"
            }
          ],
          "timestamp": "2020-12-22T15:28:09.157Z"
        },
        "soundMode": {
          "value": "Standaard",
          "timestamp": "2020-12-22T15:28:09.157Z"
        },
        "supportedSoundModes": {
          "value": [
            "Standaard"
          ],
          "timestamp": "2020-12-22T15:28:09.157Z"
        }
      },
      "audioMute": {
        "mute": {
          "value": "unmuted",
          "timestamp": "2020-12-22T15:28:09.657Z"
        }
      },
      "mediaTrackControl": {
        "supportedTrackControlCommands": {
          "value": null,
          "timestamp": "2020-08-25T20:41:40.814Z"
        }
      },
      "custom.launchapp": {},
      "samsungvd.firmwareVersion": {
        "firmwareVersion": {
          "value": "2.4.0",
          "timestamp": "2020-11-02T08:44:49.219Z"
        }
      }
    }
  }
}

**Comment by AdyRock** [comment]
OK, I should have fixed the volume up button and the "Map entry NOT found..." messages are just false warnings as those capabilities are write only. So I have added some dummy entries in the table to stop those.

As for the ambient part, I can't find any information online for that and the section in the log doesn't look promising:
```
            "custom.disabledCapabilities": {
                "disabledCapabilities": {
                    "value": [
                        "samsungvd.ambient",
                        "samsungvd.ambientContent"
                    ],
                    "timestamp": "2021-01-16T22:03:09.546Z"
                }
            },
```
Not only do the ambient bits appear to be disabled but also there are no values returned for the ambient capabilities that are there.

I will keep looking to try to find out more, but at the moment it hasn't given up it's secrets.
Unfortunately, Samsung have also changed the API recently so it no longer returns the full set of information like it used to. The old version used return the full set of commands that were supported as well as the capabilities.
