### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by Arjan-21** [AdyRock/com.smartthings#6]
When I try to add a device (washing machine) I get the message: "Connection Failed {"Statuscode": 401, "Statusmessage": "HTTPS: No Token Specified"}.

But I add the token from my SmartThings account. Is there a way to solve this problem?

**Comment by AdyRock** [comment]
Could you enable the logging, then go through the add device procedure and then send me the log.

**Comment by Arjan-21** [comment]
Thanks for your quick response.
This is my log:
* Setting logEnabled has changed.
* devices
* HTTPS Error: 401: Unauthorized
* devices

**Comment by AdyRock** [comment]
It looks like the token has not been accepted so maybe it is for the wrong account.
It can get confusing with SmartThings account and Samsung account. Can you also make sure you set the permissions correctly.

**Comment by Arjan-21** [comment]
I think that's the issue. I've a samsung account that's linked to my SmartThings. I gonna try to make a SmartThings account also.

**Comment by Arjan-21** [comment]
I think that's the issue. I've a samsung account that's linked to my SmartThings. I gonna try to make a SmartThings account also.

**Comment by Arjan-21** [comment]
It's not possible to make a new SmartThings account. They only want you to add a samsung account. and that's linked with the SmartThings.
The permissions set correctly.

**Comment by Arjan-21** [comment]
There was something wrong in my SmartThings account. Now it works really good. Made allot of flows to make the washer more smart. (don't want to get message when I'm sleeping or away etc.)
Thanks for your great app and your help!

**Comment by AdyRock** [comment]
I'm glad it is working and thanks for letting me know.
